// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqssepwgylclfzrxlscv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxc3NlcHdneWxjbGZ6cnhsc2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODY3NzYsImV4cCI6MjA2MTI2Mjc3Nn0.rc8NjzyOm_6C8JU0ofR8SdHK_kMWQ55jQz8A3z2voVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);